#!/usr/bin/env bash

SLEEP_TIME=1.2

get_current_monitor() {
    local MONITORS=$(hyprctl monitors | grep "^Monitor " | cut -d ' ' -f2)
    for m in $MONITORS; do
        if [[ $m == 'eDP-1' ]]; then
            echo 0
        elif [[ $m == 'DP-2' ]]; then
            echo 1
        elif [[ $m == 'HDMI-A-1' ]]; then
            echo 2
        fi
    done
}

get_osd_state() {
    local CURRENT_MONITOR=$(get_current_monitor)
    STATE=$(eww windows | grep osd$CURRENT_MONITOR)
    # if STATE starts with * then it's open
    [[ ${STATE:0:1} == '*' ]] && echo 'open' || echo 'closed'
}

if [[ $1 == 'close' ]]; then
    if [[ $(get_osd_state) -eq 'open' ]]; then eww close osd0; fi
else
    eww update osd_icon=$1
    eww update osd_value=$2

    if [[ $(get_osd_state) -eq 'closed' ]]; then eww open osd0; fi

    sleep $SLEEP_TIME

    if [[ $(get_osd_state) -eq 'open' ]]; then eww close osd0; fi
fi
