#!/bin/sh

killall xcape 2>/dev/null
killall easystroke
sxhkd 2>~/.config/sxhkd/.sxhkd.err &

bspc monitor eDP-1-1 -d  1 2 3 4
bspc monitor HDMI-1-1 -d 1 2 3 4
bspc wm -O eDP-1-1 HDMI-1-1

bspc config window_gap           25
bspc config border_width		 0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config removal_adjustment   true
bspc config focus_follows_pointer true
bspc config automatic_scheme 	 alternate

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a spectacle floating=on follow=on
#bspc rule -a Steam state=floating
bspc rule -a 'Friends List' state=floating
bspc rule -a Wfica_Seamless state=floating
bspc rule -a 'Citrix maximized probe window' state=floating
bspc rule -a Soffice state=tiled


xinput set-prop "SynPS/2 Synaptics TouchPad" 'libinput Tapping Enabled' 1
xinput set-prop "SynPS/2 Synaptics TouchPad" 'libinput Natural Scrolling Enabled' 1

for mouse in `xinput | grep 'Corsair' | grep 'pointer' | sed 's/.*id=\([0-9]*\).*/\1/g'`; do
	xinput set-prop $mouse "libinput Accel Profile Enabled" 0, 1 2>/dev/null
done
unset mouse

feh --bg-fill ~/Pictures/DnA7hZgU8AAxfxC.jpg:large.jpg &



xbindkeys &
redshift &
numlockx &
statnot &
~/.config/activePlayer/mediaplayers.sh 2>~/.config/activePlayer/.mediaplayer.err &
compton --config ~/.config/compton.conf 2>~/.config/.compton.err &
$HOME/.config/polybar/launch.sh 2>~/.config/polybar/.polybar.err &
libinput-gestures-setup start &
xcape -e 'Super_L=Super_L|space' &
easystroke &