#!/bin/sh

killall xcape 2>/dev/null
killall easystroke
sxhkd 2>~/.config/sxhkd/.sxhkd.err &

bspc monitor eDP1 -d  1 2 3 4 5
bspc monitor HDMI1 -d 1 2 3 4 5
bspc monitor DP1 -d 1 2 3 4 5
bspc wm -O DP1 eDP1 HDMI1

bspc config window_gap           25
bspc config border_width	 3
bspc config normal_border_color	 \#3b4252
bspc config focused_border_color \#5e81ac

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config removal_adjustment   true
bspc config focus_follows_pointer true
bspc config automatic_scheme 	 alternate
bspc config pointer_motion_interval 40

#javafx:
#bspc config honor_size_hints 	 true
bspc config honor_size_hints 	 false

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a spectacle floating=on follow=on
bspc rule -a 'Friends List' state=floating
bspc rule -a 'Steam - News' state=floating
bspc rule -a Wfica_Seamless state=floating
bspc rule -a 'Citrix maximized probe window' state=floating
#bspc rule -a '*:libreofficedev' state=tiled
#bspc rule -a '*:soffice' state=floating
bspc rule -a mijnlieff.Mijnlieff state=floating
bspc rule -a mijnlieff.interactive.matchmaking.Matchmaking state=floating
bspc rule -a mijnlieff.* state=floating
bspc rule -a mijnlieff.interactive.boardConfiguration.BoardConfiguration state=floating
bspc rule -a simplescreenrecorder state=floating
bspc rule -a processing-core-PApplet state=tiled

xrandr --output eDP1 --set "Broadcast RGB" "Full"
xrandr --output HDMI1 --set "Broadcast RGB" "Full"
xrandr --output DP1 --set "Broadcast RGB" "Full"


xinput set-prop "SynPS/2 Synaptics TouchPad" 'libinput Tapping Enabled' 1
xinput set-prop "SynPS/2 Synaptics TouchPad" 'libinput Natural Scrolling Enabled' 1

for mouse in `xinput | grep 'Logitech' | grep 'pointer' | sed 's/.*id=\([0-9]*\).*/\1/g'`; do
	xinput set-prop $mouse "libinput Accel Profile Enabled" 0, 1 2>/dev/null
	xinput set-prop $mouse "libinput Accel Speed" -0.5 2>/dev/null
done
unset mouse

feh --bg-fill ~/Pictures/ESnflJn.jpg &

xbindkeys &
redshift-gtk &
numlockx &
# statnot &
~/.config/activePlayer/mediaplayers.sh 2>~/.config/activePlayer/.mediaplayer.err &
compton --config ~/.config/compton/compton.conf 2>~/.config/.compton.err &
$HOME/.config/polybar/launch.sh 2>~/.config/polybar/.polybar.err &
libinput-gestures-setup start &
xcape -e 'Super_L=Super_L|space' &
# easystroke &

if acpi -a | grep 'off'; then
	cpupower frequency-set -g powersave
fi
