#!/bin/bash

max_brightness=$(cat /sys/class/backlight/intel_backlight/max_brightness)
brightness=$(cat /sys/class/backlight/intel_backlight/brightness)

while test $# != 0
do
    case "$1" in
        -d)
            if (($brightness >= 25)); then
			 	 let brightness=$brightness-25
			fi		
            shift
            ;;
        -u)
			if (($brightness <= $max_brightness-25)); then
				let brightness=$brightness+25
			fi
            shift
            ;;
    esac
    shift
done

echo "echo $brightness > /sys/class/backlight/intel_backlight/brightness" | sudo zsh
