env __GL_GSYNC_ALLOWED=0\
    __GL_VRR_ALLOWED=0\
    WLR_DRM_NO_ATOMIC=1\
    QT_AUTO_SCREEN_SCALE_FACTOR=1\
    QT_QPA_PLATFORM=wayland\
    QT_WAYLAND_DISABLE_WINDOWDECORATION=1\
    GDK_BACKEND=wayland\
    XDG_CURRENT_DESKTOP=river\
    GBM_BACKEND=nvidia-drm\
    __GLX_VENDOR_LIBRARY_NAME=nvidia\
    MOZ_ENABLE_WAYLAND=1\
    WLR_NO_HARDWARE_CURSORS=1\
    river > ~/.config/river/.river.err 2>&1
