#!/bin/sh

##### xrandr settings
xrandr --auto 
xrandr --output DP-4 --primary --mode 2560x1600 --rate 165.02
xrandr --output HDMI-0 --right-of DP-4 --mode 1920x1080 --rate 60.00
xrandr --output DP-2 --left-of DP-4 --mode 1920x1080 --rate 60.00

#xrandr --output DP-4 --set "Broadcast RGB" "Full"
#xrandr --output HDMI-0 --set "Broadcast RGB" "Full"
#xrandr --output DP-2 --set "Broadcast RGB" "Full"

##### bspwm desktop settings
bspc monitor DP-4 -d  1 2 3 4 5
bspc monitor HDMI-0 -d 1 2 3 4 5
bspc monitor DP-2 -d 1 2 3 4 5
bspc wm -O DP-2 DP-4 HDMI-0

##### bspc configurations
bspc config -m DP-4 window_gap 33
bspc config -m HDMI-0 window_gap 25
bspc config -m DP-2 window_gap 25

bspc config border_width	 3
bspc config normal_border_color	 \#3b4252
bspc config focused_border_color \#5e81ac

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config removal_adjustment   true
bspc config focus_follows_pointer true
bspc config automatic_scheme 	 alternate
bspc config pointer_motion_interval 17
bspc config external_rules_command "/home/zjeffer/.config/bspwm/rules/vlc.sh"
bspc config honor_size_hints 	 false

##### bspc rules
bspc rule -a Screenkey manage=off
bspc rule -a spectacle floating=on follow=on
bspc rule -a 'Friends List' state=floating
bspc rule -a 'Steam - News' state=floating
bspc rule -a 'Citrix maximized probe window' state=floating
bspc rule -a SimpleScreenRecorder state=floating
bspc rule -a 'processing-core-PApplet' state=floating focus=off
bspc rule -a 'Tk' state=floating
bspc rule -a 'Toplevel' state=floating
bspc rule -a 'Gnome-calculator' state=floating
# for origin & other wine programs
bspc rule -a "Wine" state=floating focus=off
bspc rule -a "explorer.exe" state=fullscreen

##### run programs:
#sxhkd: keyboard shortcut daemon
killall sxhkd 2>/dev/null
sxhkd &>>~/.config/sxhkd/.sxhkd.err &

#dunst: notification daemon
killall -w dunst 2>/dev/null
dunst &

#polybar: top bar
killall polybar 2>/dev/null
~/.config/polybar/launch.sh 2>~/.config/polybar/.polybar.err &

#activePlayer: keeps the current active player in a file, so it can be played using mouse keys
killall mediaplayers.sh 2>/dev/null
~/.config/activePlayer/mediaplayers.sh 2>~/.config/activePlayer/.mediaplayer.err &

#picom: compositor
killall -qw picom 2>/dev/null; picom --experimental-backends --config ~/.config/picom/picom.conf &>>~/.config/picom/.picom.err &

#nm-applet
killall nm-applet 2>/dev/null
nm-applet &

#libinput-gestures: touchpad gestures
libinput-gestures-setup restart

#xcape: set left super key to super+space, used for bringing up application launcher
killall xcape 2>/dev/null
xcape -e 'Super_L=Super_L|space' &


#feh: set desktop background
~/.fehbg &

