#!/bin/sh

##### xrandr settings
xrandr --auto 
xrandr --output eDP-1-1 --primary
xrandr --output HDMI-1-1 --right-of eDP-1-1
xrandr --output DP-1-1 --left-of eDP-1-1

xrandr --output eDP-1-1 --set "Broadcast RGB" "Full"
xrandr --output HDMI-1-1 --set "Broadcast RGB" "Full"
xrandr --output DP-1-1 --set "Broadcast RGB" "Full"

##### bspwm desktop settings
bspc monitor eDP-1-1 -d  1 2 3 4 5
bspc monitor HDMI-1-1 -d 1 2 3 4 5
bspc monitor DP-1-1 -d 1 2 3 4 5
bspc wm -O DP-1-1 eDP-1-1 HDMI-1-1

##### mouse xinput settings
xinput set-prop "SynPS/2 Synaptics TouchPad" 'libinput Tapping Enabled' 1 &
xinput set-prop "SynPS/2 Synaptics TouchPad" 'libinput Natural Scrolling Enabled' 1 &

##### bspc configurations
bspc config window_gap           25
bspc config border_width	 3
bspc config normal_border_color	 \#3b4252
bspc config focused_border_color \#5e81ac

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config removal_adjustment   true
bspc config focus_follows_pointer true
bspc config automatic_scheme 	 alternate
bspc config pointer_motion_interval 17
bspc config external_rules_command "/home/zjeffer/.config/bspwm/rules/vlc.sh"
bspc config honor_size_hints 	 false

##### bspc rules
bspc rule -a Screenkey manage=off
bspc rule -a spectacle floating=on follow=on
bspc rule -a 'Friends List' state=floating
bspc rule -a 'Steam - News' state=floating
bspc rule -a 'Citrix maximized probe window' state=floating
bspc rule -a simplescreenrecorder state=floating
bspc rule -a 'processing-core-PApplet' state=floating focus=off
bspc rule -a 'Tk' state=floating
bspc rule -a 'Toplevel' state=floating

##### run programs:
#sxhkd: keyboard shortcut daemon
killall sxhkd 2>/dev/null
sxhkd &>>~/.config/sxhkd/.sxhkd.err &

#dunst: notification daemon
killall dunst 2>/dev/null
dunst &

#polybar: top bar
killall polybar 2>/dev/null
~/.config/polybar/launch.sh 2>~/.config/polybar/.polybar.err &

#activePlayer: keeps the current active player in a file, so it can be played using mouse keys
killall mediaplayers.sh 2>/dev/null
~/.config/activePlayer/mediaplayers.sh 2>~/.config/activePlayer/.mediaplayer.err &

#picom: compositor
killall -qw picom 2>/dev/null; picom --experimental-backends --config ~/.config/picom/picom.conf &>>~/.config/picom/.picom.err &

#nm-applet
killall nm-applet 2>/dev/null
nm-applet &


#libinput-gestures: touchpad gestures
libinput-gestures-setup restart

#xcape: set left super key to super+space, used for bringing up application launcher
killall xcape 2>/dev/null
xcape -e 'Super_L=Super_L|space' &

#devmon: Automounts and unmounts optical and removable drives
#devmon &

#feh: set desktop background
~/.fehbg &

