-- Originally generated by nwg-displays on 2026-04-07 at 14:41:52.
-- Re-generate with nwg-displays or edit manually.

hl.monitor({
	output   = "desc:AOC Q27G4 18DQ9HA026322",
	mode     = "2560x1440@180",
	position = "0x0",
	scale    = "1",
	bitdepth = 10,
})

hl.monitor({
	output   = "desc:AOC Q27G4 2S6R6HA023496",
	mode     = "2560x1440@180",
	position = "2560x0",
	scale    = "1",
	bitdepth = 10,
})

hl.monitor({
	output   = "desc:DENON Ltd. DENON-AVR 0x01010101",
	mode     = "1920x1080@60",
	position = "0x-1",
	scale    = "1",
	mirror   = "DP-1",
})
