windowrule = match:title ^(Open Folder)$, float on
windowrule = match:title ^(Open File)$, float on
windowrule = match:title ^(Save As)$, float on
windowrule = match:title ^(File Operation Progress)$, float on
windowrule = match:title ^(Firefox — Sharing Indicator)$, float on
windowrule {
  name = LibreOffice
  match:class = ^(libreoffice.*)$

  suppress_event = fullscreen
  float = off
}
windowrule = match:class ^(org.gnome.Calculator)$, float on

windowrule {
  name = Rofi
  match:class = ^(Rofi)$

  float = on
  no_anim = on
}

# opacity
windowrule = match:class [gG]nome-terminal*, opacity 0.85
windowrule = match:initial_class org.wezfurlong.wezterm, opacity 0.85
windowrule = match:class kitty, opacity 0.85
windowrule = match:initial_title ^(Spotify( Premium)?)$, opacity 0.90
windowrule {
  name = VSCode
  match:class = ^([cC]ode(-[Ii]nsiders)?)$

  opacity = 0.90
}
windowrule = match:initial_class dev.zed.Zed, opacity 0.90
windowrule = match:class [Tt]hunar, opacity 0.80
windowrule = match:class [Dd]unst, opacity 0.70
windowrule = match:class [Dd]iscord, opacity 0.95

# nm connection editor
windowrule = match:class nm-connection-editor, float on
windowrule = match:class nm-openconnect-auth-dialog, float on

# protonvpn
windowrule {
  name = ProtonVPN
  match:class = protonvpn-app

  float = on
  max_size = 400 600
}

# flameshot workaround
windowrule {
  name = Flameshot
  match:title = ^(flameshot)

  move = 0 0
  float = on
  suppress_event = fullscreen
}

# steam 
windowrule {
  name = Steam - Friends List
  match:initial_title = ^(Friends List)$
  match:class = ^(Steam)$

  min_size = 320 600
  size = 400 700
  float = on
}

# Steam Tinker Launch
windowrule = match:class yad, float on

# jellyfin media player
windowrule = match:class ^(Jellyfin Media Player)$, idle_inhibit always

# thunar
windowrule {
  name = Thunar
  match:initial_title = ^(Rename.*)$
  match:class = ^([Tt]hunar)$

  float = on
  size = 600 118
  center = on
}

# gimp color selection issues
windowrule = match:class gimp, suppress_event activatefocus


windowrule {
  name = Edge Popup
  match:class = ^$
  match:title = ^$
  float = on

  no_initial_focus = yes
  no_focus = yes
  no_anim = yes
  no_shadow = yes
  border_size = 0
  rounding = 0
  stay_focused = yes
}